title: Matthew Akino-Wittering
subtitle: Product Manager
email: matthew.akinowittering@outlook.com
description: 'Hello, I’m Matthew and this is my corner of the Internet.'
baseurl: ''
url: 'https://matthew.akinowittering.com'
author:
  name: Matthew Akino-Wittering
  links:
    - url: 'https://www.linkedin.com/in/matthewwittering/'
      label: LinkedIn
      icon: fa-brands fa-linkedin
    - url: 'https://bitbucket.org/snippets/mjakinowittering/'
      label: BitBucket
      icon: fa-brands fa-bitbucket
    - url: 'https://dribbble.com/mjakinowittering/likes'
      label: Dribbble
      icon: fa-brands fa-dribbble
    - url: 'https://github.com/mjakinowittering'
      label: GitHub
      icon: fa-brands fa-github
    - url: 'https://www.scrumalliance.org/community/profile/mwittering'
      label: Scrum Alliance
      icon: fa-solid fa-globe
    - url: 'https://twitter.com/mjwittering'
      label: Twitter
      icon: fa-brands fa-twitter
permalink: '/:categories/:title/'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
jekyll_tidy:
  exclude:
    - '**/*.css'
    - '**/*.css.map'
    - '**/*.js'
    - '**/*.js.map'
    - '**/*.scss'
plugins:
  - jekyll-tidy
  - jekyll-timeago
collections:
  education:
    output: false
    permalink: '/education/:title:output_ext'
  employment:
    output: false
    permalink: '/employment/:title:output_ext'
  hobbies:
    order:
      - programming.md
      - podcasts.md
    output: false
    permalink: '/hobbies/:title:output_ext'
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - package.json
  - package-lock.json
  - vendor/
