services:
  jekyll:
    container_name: matthew-akinowittering-com
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll:z
      - ./vendor/bundle:/usr/local/bundle:z
    ports:
      - 4000:4000
      - 35729:35729
    command: jekyll serve --livereload
